### ISSUE TITLE
Event Prediction Type

### ISSUE THREAD

**Issue by arunksagotra** [ant-research/EasyTemporalPointProcess#11]
Hi,

How we can predict on test data and get each event prediction type.

**Comment by iLampard** [comment]
Hi,

when you run the example script https://github.com/ant-research/EasyTemporalPointProcess/blob/main/examples/train_nhp.py, in the pipeline, the model will predict on test data as well and the accuracy metrics denotes the event prediction type accuracy on test data.

**Comment by iLampard** [comment]
There is also another way to do this. 

Given a trained model, you can directly evaluate it on test date. See this example https://github.com/ant-research/EasyTemporalPointProcess/blob/main/docs/source/user_guide/run_eval.rst (the online docs fail to update, see this source file)

**Comment by arunksagotra** [comment]
I want to see the predicted event type and want to compare with the ground truth. In the evaluation config file I can see only the model accuracy.

**Comment by iLampard** [comment]
> I want to see the predicted event type and want to compare with the ground truth. In the evaluation config file I can see only the model accuracy.

The batch-wise values for predicted event type is here. 
see https://github.com/ant-research/EasyTemporalPointProcess/blob/main/easy_tpp/torch_wrapper.py#L143

In the runner they are concatenated together and fed into the metrics calculations.
see https://github.com/ant-research/EasyTemporalPointProcess/blob/main/easy_tpp/runner/tpp_runner.py#L168
