### ISSUE TITLE
Exact value of experiments.

### ISSUE THREAD

**Issue by liu-yang-maker** [ant-research/EasyTemporalPointProcess#15]
EasyTPP is a wonderful work in this domain and provide a perfect benchmark for us. We would like to use easyTPP as our backbone, could you provide the exact value in all the dataset you used with various models? If so, we can be more convenience. Thanks a lot!

**Comment by iLampard** [comment]
Hi, i will update the online doc to put the exact value there. 

Be noted that the results could be continually updated as we may either improve the data or fix reported bugs in our package.

**Comment by iLampard** [comment]
Hi, we have updated the paper in arxiv and the numbers are provided in the main text or the appendix.  See https://arxiv.org/abs/2307.08097. 

again, we will keep updating / correcting the numbers and put them in the online docs.
