### ISSUE TITLE
Time Resolution for each dataset

### ISSUE THREAD

**Issue by zhjcp** [ant-research/EasyTemporalPointProcess#16]
Hello, I would like to ask what is the time resolution for each dataset (in seconds/minutes/hours/days/months/years or ...) ?

**Comment by iLampard** [comment]
Hi, to confirm the resolution of the dataset you should check out the original papers.  We did not change the resolution or other key properties of the data. What we have done is only formatting or cleaning, to let it compatible with our package.

**Comment by zhjcp** [comment]
Ok, thank you for the response.
