### ISSUE TITLE
Earthquake Dataset

### ISSUE THREAD

**Issue by JZ7722** [ant-research/EasyTemporalPointProcess#18]
Hi! 
Thank you so much for developing the dataset. 
I am currently trying to understand the information in the earthquake dataset and trying to find the specific source of it. However, when I checked the usgs website, I encountered some difficulties. 

When you mention timestamped earthquake events, how exactly did you collect timestamped earthquake events data from the USGS website? You from a web page (https://earthquake.usgs.gov/earthquakes/search/) to collect, or use libcomcat - python library collection?

If you use the website to collect, what search options have you set up? If you are using the libcomcat-python library on python to collect, could you please share the relevant code for collecting timestamped earthquake events data? please. 
I would appreciate it if you could share some more detailed information on collecting timestamped earthquake events data.
Thank you very much.

**Comment by iLampard** [comment]
Hi, 

i used the web https://earthquake.usgs.gov/earthquakes/search/ to collect the data. 

The setting is Magnitude: 2.5+, Date & Time: set to max horizons (3 or 4 years) ,  Geographic Region: Conterminous U.S. 

I reset the time horizon to get a few files and i process them into sequences. The script is here: https://github.com/ant-research/EasyTemporalPointProcess/blob/main/examples/script_data_processing/earthquake.py.

It has been done several months ago and some original csvs have been lost. If you have a better preprocessed dataset, i would like to replace it with the current one.

**Comment by JZ7722** [comment]
Thank you very much for your help. If I have a better preprocessed dataset, I will share it with you.
