### ISSUE TITLE
self.time_factor in ODETPP class (torch_ode_tpp.py)

### ISSUE THREAD

**Issue by HojunYou** [ant-research/EasyTemporalPointProcess#19]
Hello, thank you for such a great python library.

I've been reviewing the ODETPP class in torch_ode_tpp.py and I'm curious about the role of self.time_factor.
To the best of my knowledge, there is no such thing in the reference code, but I found out that this factor critically impacts the likelihood score. 
If possible, could you explain the reasoning behind implementing self.time_factor? Understanding its purpose would be very helpful.

Thank you in advance!

**Comment by iLampard** [comment]
Hi,  

Without this time factor, it may generate instability during training (especially in tf version). To make tf and torch version comparable, i put these in both versions of ODETPPs.

**Comment by HojunYou** [comment]
Yes. That's my observation as well with pytorch. 

My question is let's say we have t_0 and t_1 and we want to know the value of z(t_1), which is the latent state at t_1. If we feed dt = dt/10 (self.time_scale = 10) into NeuralODE,  then we evaluate z(t_0+(t_1-t_0)/10) while our goal is to evaluate z(t_1). So, we should either repeat this 10 times to reach t_1 or drop 'time_scale' and increase the number of NeuralODE evaluations.

I hope this makes sense to you and I'm happy to hear back from you.
Thank you!

**Comment by iLampard** [comment]
yes, it makes sense. pls make a pr to the repo if you already have the fix. Thanks.

**Comment by HojunYou** [comment]
I figured it would be better to say how to fix this as it is very simple.

I recommend that you just remove self.time_factor in the python script and increase 'ode_num_sample_per_step' in configuration files (.yaml) because solving a neural ODE with finer discrete step sizes would be more efficient.
Let me know if your understanding is different from mine.

**Comment by iLampard** [comment]
Hi,  i remove the time_factor in torch version. 

For tf version, i keep it for the moment as it runs too slow if i put a large number of sample per step. I will figure it out later. 

Thanks for your advise.
