### ISSUE TITLE
Add paper

### ISSUE THREAD

**Issue by 943fansi** [ant-research/EasyTemporalPointProcess#2]
[META TEMPORAL POINT PROCESSES](https://arxiv.org/abs/2301.12023)

**Comment by iLampard** [comment]
Hi, for the moment, i'm still busy improving the existing code for easier use. 

However, we welcome the contribution from the community if anyone is interested in implementing this new model.

**Comment by iLampard** [comment]
Hi, as committed, we will try to implement this paper soon.
