### ISSUE TITLE
Next Event Prediction (about event type)

### ISSUE THREAD

**Issue by zhjcp** [ant-research/EasyTemporalPointProcess#20]
Hello! My question is below:
- In Appendix B.2 of the EasyTPP paper, it is written: "More precisely, for each event in each held-out sequence, we attempt to predict its time given only the preceding events, as well as its type given both its true time and the preceding events." According to this approach, when predicting the type of the next event, the true time of the next event should be input. However, in your code implementation (line 186 of torch_basemodel.py), the 'sample_dtimes' parameter passed to the function compute_intensities_at_sample_times() is the predicted event time by the model (i.e., 'dtimes_pred'), rather than the true time (i.e., 'time_delta_seq'). Is there a problem here?

**Comment by iLampard** [comment]
Hi,

the type prediction is an integral over sampled intensities, which relies on discretized times (this refers to sample_dtimes). A rigorous explanation can be found at section 4 for Neural Hawkes Process: https://arxiv.org/pdf/1612.09328.pdf.

 I agree the wording here might be a little bit misleading and will improve it in the next version.

**Comment by zhjcp** [comment]
Thanks for you feedback.
- Yes, in Section 4 of NHP, the type prediction is an integral over sampled intensities. However, this is for type prediction given only historical events without specifying the timestamp of the next event. In EasyTPP, according to Appendix B.2, the timestamp of the next event is also provided along with historical events. Specifically, my question is, why does Appendix B.2 mention providing the true timestamp of the next event, while the code provides the predicted timestamp of the next event ?

**Comment by iLampard** [comment]
Hi, 

i indeed find the wording in B.2 is misleading. No true timestamps should be provided in computation because we aim to  calculate the type and time without the knowledge of true event.

**Comment by zhjcp** [comment]
OK. Thanks for your feedback.
