### ISSUE TITLE
Ways of reducing GPU VRAM / CPU memory usage

### ISSUE THREAD

**Issue by tunajaw** [ant-research/EasyTemporalPointProcess#21]
Hi, thanks for providing this useful TPP benchmark!

Currently, I'm trying to apply this benchmark to my own dataset; however, I'm facing GPU OOM issues for most of the TPP models using GPU, which ran out of over 24GB of GPU VRAM. For those TPP models using CPU to train, the thread running the model was killed since it consumed more than 250GB of CPU RAM. I'd like to know if there are any solutions to this issue.

Dataset:
K ~ 300
N ~ 4,000
avg. event length of each sequence ~ 100

Training:
batch_size = 2

**Comment by iLampard** [comment]
hi, 

The code indeed has not been optimized for training or inference: e.g., when the sequence is long, the attention involves too heavy computation as it is simply a naive implementation.  For the moment, for alleviate your problem, you can reduce the hidden size used in the model to 16 or event 8.  

We do consider to introduce more efficient structures into our code, such as flash attention or kv cache.
