### ISSUE TITLE
Amazon dataset source

### ISSUE THREAD

**Issue by yinzhu-quan** [ant-research/EasyTemporalPointProcess#24]
<img width="1137" alt="截屏2024-05-14 23 31 27" src="https://github.com/ant-research/EasyTemporalPointProcess/assets/78992511/4b2412ec-aa32-4757-a0fa-a624e8bca4d6">

Amazon has the same data source as Taobao. From the reference of Amazon, we cannot get the dataset description.

**Comment by iLampard** [comment]
Hi， 

i will correct the source in README.

What kind of description do you need exactly?  This lines of description is still not enough for you?

**Comment by iLampard** [comment]
For more details on Amazon, pls see [issue-14](https://github.com/ant-research/EasyTemporalPointProcess/issues/14)

**Comment by yinzhu-quan** [comment]
Hi,

Thanks for your reply! It would be helpful for us to understand if you could provide specific event types, as referred to in the following figure. We are familiar with the event types in Amazon datasets, but we would like to know about the event types in other datasets, such as Retweet, taxi, etc. :)

<img width="262" alt="截屏2024-05-15 07 15 54" src="https://github.com/ant-research/EasyTemporalPointProcess/assets/78992511/6d9a8e87-ae1e-4d92-b93c-a211bfc6c8e2">
