### ISSUE TITLE
Specific event types for Datasets

### ISSUE THREAD

**Issue by yinzhu-quan** [ant-research/EasyTemporalPointProcess#25]
Hi there,

It will be helpful for us if you could provide us with some description texts for event types w.r.t. Retweet, Taxi, StackOverflow, and Taobao datasets. We are trying to understand the datasets better. We saw something similar to #14.

Thanks! :)

**Comment by yinzhu-quan** [comment]
Hi,

It will be helpful for us to understand if you could provide the corresponding event category to each event type index is available. For example, in #14, you provide us 0 - Clothing, 1 - Shoes, 2 - Accessories, 3 - Jewelry...

Thanks! :)

**Comment by iLampard** [comment]
Hi, 

For Retweet, Taxi and SO, i simply copy them from original authors' repo and i have no further information to share for the moment. 

For Taobao, the original data has masked the event type description (see https://tianchi.aliyun.com/dataset/649) so no textual information can be provided. I group the events based on cate id.

**Comment by yinzhu-quan** [comment]
Thanks for your reply! I really appreciate it. :)
