### ISSUE TITLE
Time Positional Encoding

### ISSUE THREAD

**Issue by zefang-liu** [ant-research/EasyTemporalPointProcess#26]
Thanks a lot for sharing this great repo! In the [`TimePositionalEncoding`](https://github.com/ant-research/EasyTemporalPointProcess/blob/5d46df105ff91aae773962871ea635c478f4e82f/easy_tpp/model/torch_model/torch_baselayer.py#L95) for `THP`, are timestamps needed in the sine and cosine functions? It seems that the current implementation uses the position indices compared with the [original implementation](https://github.com/SimiaoZuo/Transformer-Hawkes-Process/blob/9f2e563909c538302733f048131ae8c535ce02ec/transformer/Models.py#L61).

**Comment by iLampard** [comment]
Hi, 

You mean in easytpp, the stamps are not included in the sin/cosine, which is inconsistent with his paper? 

if you have a fixed version, welcome to issue a pr. otherwise i will fix it sooner or later.

**Comment by iLampard** [comment]
thanks for the pr
