### ISSUE TITLE
About the RMSE and Type Error Rate Values

### ISSUE THREAD

**Issue by zhjcp** [ant-research/EasyTemporalPointProcess#29]
Hello,

I am somewhat puzzled as to why the RMSE and Type Error Rate for different models in your paper, EasyTPP, appear so close to each other, yet there are quite noticeable differences in their respective papers.

**Comment by iLampard** [comment]
Hi, 

The numbers are indeed close based on what we have implemented... so we conclude that there is no consistent winners across the datasets ..
