### ISSUE TITLE
multivariate tpp

### ISSUE THREAD

**Issue by nchesk** [ant-research/EasyTemporalPointProcess#3]
hi, thank you for your awesome work

I was wondering if this library can handle multivariate tpp?
And in case the answer is no and you don't have plans to add such functionatile, would you be able to point to me how can I do it myself?

**Comment by iLampard** [comment]
Hi, 

what do you mean by multivariate tpp? 

in my views, multivariate tpp refers to tpp with multi event types, which is already supported in the framework.

**Comment by iLampard** [comment]
example:  train a NHP on taxi data which has 10 event types.
code: https://github.com/ant-research/EasyTemporalPointProcess/blob/main/examples/train_nhp.py

**Comment by nchesk** [comment]
I mean when event has not only type, but another features

**Comment by iLampard** [comment]
Hi, 

This is not supported yet, because there is no standard way to do this: the features may be either dense or sparse or a mix of dense and sparse, which results in a complex way of modeling.

Do you have a data sample?  I try to give you a simple example of customizing the code.

**Comment by iLampard** [comment]
Hi, 

This is not supported yet, because there is no standard way to do this: the features may be either dense or sparse or a mix of dense and sparse, which results in a complex way of modeling.

Do you have a data sample?  I try to give you a simple example of customizing the code.

**Comment by nchesk** [comment]
For example, let’s say I have a dataset of loans.
I don’t want to just predict sum of loans for period( in this case I could’ve just use time series), but I want to predict structure of loans(at least sum, rate and term)
Thank you for your time!

**Comment by 943fansi** [comment]
@nchesk https://github.com/dunan/MultiVariatePointProcess

**Comment by iLampard** [comment]
@nchesk   

Sorry for the late reply.   

I add an example here: https://github.com/ant-research/EasyTemporalPointProcess/blob/main/examples/train_nhp_with_features.py

It is a simplified example where i have hacked a lot of code. I will optimize the package later so that user can more easily to do the 'multivariate tpp' in your context.

**Comment by iLampard** [comment]
i close this as this is no further response
