### ISSUE TITLE
Hyper-Parameter Settings For Each Model

### ISSUE THREAD

**Issue by zhjcp** [ant-research/EasyTemporalPointProcess#30]
Hello,

I used the parameter configuration from experiment_config.yaml, but it seems that I cannot replicate the experimental results in the paper. Could you provide the actual parameter settings for each neural point process used in the paper?

**Comment by iLampard** [comment]
Hi, 

The models have been continuously modified due to bugs found or different implementations from the original ones.  I will republish a config with whole set the params in the near future.
