### ISSUE TITLE
AttNHP train with GPU

### ISSUE THREAD

**Issue by samiemostafavi** [ant-research/EasyTemporalPointProcess#40]
Hi,

I am trying the AttNHP model with GPU but the following error shows up before the training starts:

` File ".../EasyTemporalPointProcess/easy_tpp/model/torch_model/torch_attnhp.py", line 168, in make_combined_att_mask
    combined_mask = torch.cat([attention_mask, layer_mask], dim=-1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument tensors in method wrapper_CUDA_cat)`

I am running the taxi dataset as the instructions.
Python 3.9.19
Pytorch 2.4.1+cu121

Best,
Samie

**Comment by zefang-liu** [comment]
I also met this issue. It seems `layer_mask` and `attention_mask` in AttNHP were not in the CUDA device. I will submit a PR.

**Comment by iLampard** [comment]
PR merged
