### ISSUE TITLE
Issues about NYC taxi dataset

### ISSUE THREAD

**Issue by waystogetthere** [ant-research/EasyTemporalPointProcess#42]
Hi! Thanks for your great work!

I am wondering if the NYC taxi datasets (with 10 types) have clear event type meaning. As I found that the type 1~5 should be drop off at 5 boroughs, and the 6-10 should be pick-up at 5 boroughs. They always occur in tandem. But I don't know which borough they refer to.  Thanks a lot!

**Comment by iLampard** [comment]
Hi, 

For taxi data, i simply copied them from the original authors without knowing the exact meaning of event types. You have to consult them for any further information.

See the similar issue before 
https://github.com/ant-research/EasyTemporalPointProcess/issues/25
