### ISSUE TITLE
Multivariate Hawkes Process implementation

### ISSUE THREAD

**Issue by cb6e310** [ant-research/EasyTemporalPointProcess#44]
Thank you for this excellent foundation work. I would like to use your library as a toolkit for baseline benchmark. But I could not find the implementation of the Multivariate Hawkes Process mentioned in your paper, thank you very much for looking into this problem.

**Comment by HaochenWang1243** [comment]
I think multivariate hawkes process isn't considered state-of-the-art so it's not implemented here. I suggest using [tick](https://github.com/X-DataInitiative/tick) for it.

**Comment by iLampard** [comment]
It is not implemented here because it is not neural model. You can just use the tick library.
