### ISSUE TITLE
The SAHP result in the paper cannot be reproduced

### ISSUE THREAD

**Issue by ykzhao** [ant-research/EasyTemporalPointProcess#46]
Hi, I noticed that the SAHP has been updated recently. However, the NLL and ACC results in the paper cannot be reproduced for the new code. I have tested retweet and amazon datasets. Both NLL and ACC are far more worse than the number shown on paper. Is there a problem still with the code or is there a problem with the result shown on paper? 
Note that the hyperparameter are strictly followed the paper.
Thanks!

**Comment by iLampard** [comment]
Hi,  the loglike code needs to be improved. we will fix it very soon and re-publish the test results in the documentation.
