### ISSUE TITLE
Question about the exact event type for the retweet dataset

### ISSUE THREAD

**Issue by yuzhenmao** [ant-research/EasyTemporalPointProcess#47]
Hi! Thank you for the amazing work! 

I am wondering if it is possible to get the exact event type for the retweet dataset. In the current data file, we can only get the event type ID (i.e., 0, 1, 2), but the mapping between ID and the exact type is missing. I found several similar issues: #14 #24 #25, and these types of questions seem highly meaningful. Thank you for the help!

**Comment by iLampard** [comment]
Hi,

Please see the paper of [NHP](https://arxiv.org/pdf/1612.09328) for the event type mapping for Retweet data: page 20, section C.5.

**Comment by yuzhenmao** [comment]
Thank you for the reply! I noticed that the retweet dataset in EasyTPP is a little different from the data in the original paper's repo. May I ask if the label set is shared between these two versions? Based on the details in the original paper, the mapping should be {0: small, 1: medium, 2: large}.
