### ISSUE TITLE
Implementation of OTD

### ISSUE THREAD

**Issue by amartyamukherjee** [ant-research/EasyTemporalPointProcess#50]
Could you disclose your implementation of the optimal transport distance (OTD)? I was unfortunately unable to find an implementation of that in this repository. Thanks!

**Comment by iLampard** [comment]
Hi,

OTD function can be found at https://github.com/iLampard/hypro_tpp/blob/main/hypro_tpp/utils/metrics.py#L148, which is in fact copied from https://github.com/hongyuanmei/neural-hawkes-particle-smoothing/blob/8f33c75038e739a2a0b61db854dd97d918ce2d19/nhps/distance/utils/edit_distance.py.   

The explanation can be found the paper of https://arxiv.org/abs/1905.05570.

**Comment by amartyamukherjee** [comment]
I appreciate the reference. In EasyTPP, the task focuses on predicting the next 5 or 10 events given previous events, which raises some questions for me about the specifics of the OTD (or 1-Wasserstein distance) computation in this context, especially in comparison to Neural Hawkes Particle Smoothing. Since we’re not deleting or inserting events in your setup, it seems that the OTD computation could potentially be simplified.

Below, I’ve attached my current interpretation of how the OTD might be computed based on my understanding. Please let me know if I’ve overlooked any important details.

Thank you again for your time!

<img width="932" alt="Screenshot 2024-11-12 at 3 38 02 PM" src="https://github.com/user-attachments/assets/cd3d5d35-b735-46b2-bd0a-1cb94a7a053f">

**Comment by amartyamukherjee** [comment]
Thank you very much for your prompt reply! Could you let me know what values you assigned to the parameters del_cost, trans_cost in EasyTPP?

**Comment by iLampard** [comment]
Hi, 

you can use 

trans_cost = 1.0 
del_cost either be 1.0 or 0.5. 

Note that we have updated the code in batch-wise multi-step sampling recently, you are welcome to post the new results on these datasets.
