### ISSUE TITLE
Problems with model config

### ISSUE THREAD

**Issue by tsebaka** [ant-research/EasyTemporalPointProcess#6]
Hello!
I have some troubles with config. I don't know how to put config in model:
I need to define a IntensityFree model:

from omegaconf import OmegaConf
conf = OmegaConf.load('experiment_config.yaml')
model = IntensityFree(conf['IntensityFree'])
...
Errors
...
Can you help?

And you have typo right here ->
<img width="501" alt="image" src="https://github.com/ant-research/EasyTemporalPointProcess/assets/78146236/93f72eae-66f6-4b2b-b613-364f21448435">

**Comment by iLampard** [comment]
what is omegaconf?   i have not used it before. 

the error is possibly because of the config parsing problem. 

The easiest way is to use this script

https://github.com/ant-research/EasyTemporalPointProcess/blob/main/examples/train_nhp.py

when putting the correct experiment id to call intensity free model.

let me know if you still have a problem.

**Comment by tsebaka** [comment]
omegaconf - yaml and etc parser
like
# adam.yaml
optimizer:
  type: "Adam"
  lr: 0.001

import hydra
from omegaconf import DictConfig
@hydra.main(config_path=".", config_name="config")
def main(cfg: DictConfig):
    print(cfg.optimizer.type)
if __name__ == "__main__":
    main()
convenient
---
I didn't work with this types of model training (scripts)
I want work like a PyTorch style
model = NHP(config), I don't know how I can take config (If I take conf from your script: AttributeError: 'RunnerConfig' object has no attribute 'loss_integral_num_sample_per_step')
...
for batch in dl:
    model.forward()
...

**Comment by iLampard** [comment]
The runner takes care of processing and assigning values to models, based on parsed configs.

I will have a look at your case and reply to you shortly.

**Comment by iLampard** [comment]
Hi, i add a script here. Please have a look

https://github.com/ant-research/EasyTemporalPointProcess/blob/main/examples/train_nhp_omegaconf.py

Also thanks for pointing the typo. It has been fixed.

**Comment by tsebaka** [comment]
thank you!
