### ISSUE TITLE
Taxi dataset

### ISSUE THREAD

**Issue by rvandewater** [ant-research/EasyTemporalPointProcess#7]
Hi,

Thank you for developing this package. I was trying to get started and was wondering where to get the taxi dataset. It does not seem to be on google drive:
![image](https://github.com/ant-research/EasyTemporalPointProcess/assets/23501069/654c835a-d798-4533-a0dc-a7294c6ec25f)
Also, could you point me to how to select datasets from the default config (if you do not have all of the datasets in the right directory)? Thank you!

**Comment by rvandewater** [comment]
Apparently the right link is in the paper: https://drive.google.com/drive/u/0/folders/1f8k82-NL6KFKuNMsUwozmbzDSFycYvz7.

**Comment by iLampard** [comment]
Hi, in ReadME file,  i indeed put this link. https://drive.google.com/drive/u/0/folders/1f8k82-NL6KFKuNMsUwozmbzDSFycYvz7.  

In short future, we will put the processed data in huggingface instead of Google drive so it will be easy to find and use them.
